config/routes.rb
Lunch::Application.routes.draw do
  resource :car_options
  resources :votes
  resources :people
  resources :places
  match 'periodic' => 'places#periodic'
  
  match 'login' => 'people#login', :as => :login
  match 'logout' => 'people#logout', :as => :logout
  match 'profile' => 'people#edit', :as => :profile

  root :to => "places#index"

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_secure_password
  validates :password, presence: { on: :create }

  has_one :vote, dependent: :destroy
  has_one :place, through: :vote
  has_one :car
  has_one :membership # for now, just one
  has_one :group, through: :membership
  
  has_many :places
  has_many :visible_places, through: :group, source: :places, order: 'votes_count desc'
  
  validates :name, presence: true, uniqueness: true
  
  before_validation { write_attribute :name, name.try(:strip) }
  
  before_create :ensure_group

  def update_car_options(options = {})
    self.has_car = options[:has_car]

    if has_car
      self.car ||= build_car
      car.seats = options[:seats]
      return false unless car.save

      if has_car_changed? and vote and vote.car.nil?
        vote.update_attribute :car, car
      end
    end

    save
  end
  
  private
    def ensure_group
      self.group = Group.first unless group
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  respond_to :html
  before_filter :login_required, only: [:edit, :update]
  
  def new
    @person = Person.new
  end
  
  def create
    @person = Person.create(params[:person].merge(signup_ip: request.remote_ip))
    if @person.valid?
      session[:user_id] = @person.id
      respond_with(@person, location: places_url)
    else
      render :new
    end
  end
  
  def edit
    redirect_to edit_person_url(@current_user.id) unless current_user?
  end
  
  def update
    raise "Cannot update another user's profile" unless current_user?
    
    @current_user.attributes = params[:person]
    if @current_user.save
      respond_with(@current_user, location: places_url)
    else
      render :edit
    end
  end
  
  def login
    if request.post?
      @current_user = Person.find_by_name(params[:name]).try(:authenticate, params[:password])
      if @current_user
        session[:user_id] = @current_user.id
        @current_user.login_ip = request.remote_ip
        @current_user.save
        redirect_to places_url
      else
        flash.now[:error] = t('people.login.failed')
      end
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to login_url
  end

  private
    def current_user?
      params[:id].to_i == @current_user.id
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">&nbsp;</div>
    <div class="person-form span6">

      <%= form_for @current_user, html: {class: 'form-horizontal'} do |f| -%>
        <fieldset>
          <legend><%=t '.heading' %></legend>

          <% unless @current_user.errors.empty? %>
          <div class="alert alert-error alert-block">
            <h4 class="alert-heading">Your sign up was unsuccessful</h4>
            <p>There were the following problems:</p>
            <ul>
              <% @current_user.errors.full_messages.each do |m| -%>
              <li><%= m %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="control-group">
            <%= f.label :name, class: 'control-label' %>
            <div class="controls">
              <%= f.text_field :name, autofocus: true %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :password, class: 'control-label' %>
            <div class="controls">
              <%= f.password_field :password %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :password_confirmation, class: 'control-label' %>
            <div class="controls">
              <%= f.password_field :password_confirmation %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit class: 'btn btn-primary btn-large' %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/people/login.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">&nbsp;</div>
    <div class="person-form span6">

      <form action="<%= login_url %>" method="post" class="form-horizontal">
        <fieldset>
          <legend><%=t '.heading' %> <small> <%=t '.signup_html', path: new_person_path %></small></legend>
          <div class="control-group">
            <%= label_tag :name, Person.human_attribute_name(:name), class: 'control-label' %>
            <div class="controls">
              <%= text_field_tag :name, '', autofocus: true %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :password, Person.human_attribute_name(:password), class: 'control-label' %>
            <div class="controls">
              <%= password_field_tag :password %>
            </div>
          </div>

          <div class="form-actions">
            <%= submit_tag t(".submit"), class: 'btn btn-primary btn-large' %>
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">&nbsp;</div>
    <div class="person-form span6">

      <%= form_for @person, html: {class: 'form-horizontal'} do |f| -%>
        <fieldset>
          <legend><%=t '.heading' %></legend>

          <% unless @person.errors.empty? %>
          <div class="alert alert-error alert-block">
            <h4 class="alert-heading">Your sign up was unsuccessful</h4>
            <p>There were the following problems:</p>
            <ul>
              <% @person.errors.full_messages.each do |m| -%>
              <li><%= m %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="control-group">
            <%= f.label :name, class: 'control-label' %>
            <div class="controls">
              <%= f.text_field :name, autofocus: true %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :password, class: 'control-label' %>
            <div class="controls">
              <%= f.password_field :password %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :password_confirmation, class: 'control-label' %>
            <div class="controls">
              <%= f.password_field :password_confirmation %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit class: 'btn btn-primary btn-large' %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>