config/routes.rb
Lunch::Application.routes.draw do
  resource :car_options
  resources :votes
  resources :people
  resources :places
  match 'periodic' => 'places#periodic'
  
  match 'login' => 'people#login', :as => :login
  match 'logout' => 'people#logout', :as => :logout
  match 'profile' => 'people#edit', :as => :profile

  root :to => "places#index"

end

app/models/place.rb
require 'rdiscount'

PlaceCar = Struct.new(:owner, :votes)

class Place < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :person, presence: true

  belongs_to :person

  has_many :votes, dependent: :destroy
  has_many :people, through: :votes

  before_validation { write_attribute :name, name.try(:strip) }

  attr_protected :person_id

  def self.most_popular
    self.where('votes_count > 0').order('votes_count desc').first
  end

  def formatted_notes
    notes and Markdown.new(notes).to_html.html_safe or ""
  end

  def car_owners
    owners = {}
    people.select(&:has_car?).each do |person|
      owners[person] = []
    end
    owners[nil] = []

    votes.each do |vote|
    	car_owner = vote.car.try(:person)
    	car_owner = nil unless owners.has_key? car_owner
    	owners[car_owner] << vote
    end

    owners.delete(nil) if owners[nil].empty?
  	owners
  end

  # This is used for the JSON API
  def cars
    cars = []
    car_owners.each do |p, v|
      cars << PlaceCar.new(p, v)
    end
    cars
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  respond_to :html, :js, :json
  before_filter :login_required

  def index
    load_places_data

    @new_place = Place.new
    respond_with @places
  end

  def show
    @place = @current_user.group.places.find(params[:id])
    respond_with @place
  end

  def periodic
    load_places_data
    render partial: 'places'
  end

  def create
    @place = @current_user.places.create(params[:place])
    respond_with(@place)
  end

  def edit
    @place = @current_user.places.find(params[:id])
  end

  def update
    @place = @current_user.places.find(params[:id])
    @place.attributes = params[:place]
    @place.save
  end

  def destroy
    @place = @current_user.places.find(params[:id])
    @place.destroy

    respond_with(@place)
  end

  private
    def load_places_data
      @places = @current_user.visible_places.to_a

      @my_place = @current_user.place
      @their_place = @current_user.group.places.most_popular

      @places.delete(@my_place)
      @places.delete(@their_place)
    end

end

app/helpers/places_helper.rb
module PlacesHelper
  def car_list(owner, votes)
    render partial: 'places/car_list', locals: {owner: owner, votes: votes}
  end

  def tab_active(place, tab)
    active_tab = params[place.id.to_s]
    return " active" if tab.start_with?('info') and !active_tab
    if active_tab and active_tab == tab
      " active"
    else
      ""
    end
  end

  def car_active(place)
    if params[place.id.to_s].try(:start_with?,'car')
      " active"
    else
      ""
    end
  end
end

app/views/places/_car_list.html.erb
<h4>
  <% if owner %>
    <i class="icon-road"></i>
    <%= owner.name %>
  <% else %>
    No Car Chosen
  <% end %>

  <% if owner %>
  <span class="label"><%= owner.car.seats_left %> left</span>
  <% end %>
</h4>

<ul class="unstyled">
  <% votes.each do |v| %>
  <li>
    <%= v.person.name %>
    <% unless v.comment.blank? %>
      <a href="#" rel="tooltip" title="<%= v.comment %>"><i class="icon-comment"></i></a>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/places/_place.html.erb
<%= form_for place, remote: true, html: {class: 'form-horizontal'} do |f| -%>

<div class="modal-header">
  <a class="close" data-dismiss="modal">x</a>
  <h3><%= place.new_record? and "Add a New Place" or "Edit a Place" %></h3>
</div>

<div class="modal-body">

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, disabled: !place.new_record? %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :notes, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, rows: 4, class: 'span3' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :walkable, class: 'control-label' %>
    <div class="controls">
      <label class="checkbox">
        <%= f.check_box :walkable %>
        This place is within walking distance.
      </label>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :leaving_at, class: 'control-label' %>
    <div class="controls">
      <%= f.time_select :leaving_at, {minute_step: 15, ampm: true}, {class: 'input-small'} %>
    </div>
  </div>

</div>

<div class="modal-footer">
  <button class="btn" data-dismiss="modal">Cancel</button>
  <button class="btn btn-primary">Save Changes</button>
</div>

<% end %>

app/views/places/_place_cell.html.erb
<div class="span3 place-cell" id="place<%=place.id%>">
  <div class="tabbable tabs-below">
    <div class="well">

    <div class="btn-group pull-right">
      <%= link_to '<i class="icon-ok"></i>'.html_safe, votes_path(:place => place), method: :post, remote: true, class: 'btn btn-mini' %>
      <% if @current_user == place.person %>
        <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_place_path(place), remote: true, class: 'btn btn-mini' %>
        <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, place_path(place), method: :delete, confirm: t('places.destroy.confirm'), remote: true, class: 'btn btn-mini btn-danger' %>
      <% end %>
    </div>

      <h3><%= place.name %></h3>
      <%= place.formatted_notes %>

      <div class="tab-content">
        <% tab = "info#{place.id}" %>
        <div class="tab-pane<%= tab_active place, tab %>" id="<%=tab%>">
          <dl class="dl-horizontal">
            <dt>Added by</dt>
            <dd><%= place.person.name %></dd>

            <% if place.leaving_at %>
              <dt>Leaving</dt>
              <dd><%= place.leaving_at.to_s(:time) %></dd>
            <% end %>

            <dt>Distance</dt>
            <dd><%= place.walkable? and t('.walking') or t('.driving') %></dd>
          </dl>
        </div>

        <% if place.walkable? %>

          <% tab = "people#{place.id}" %>
          <div class="tab-pane<%= tab_active place, tab %>" id="<%=tab%>">
            <h4><%= pluralize(place.people.count, 'person is', 'people are') %> going</h4>
            <ul class="unstyled">
              <% place.people.each do |person| %>
              <li><%= person.name %></li>
              <% end %>
            </ul>
          </div>

        <% else %>

          <% place.car_owners.each do |owner, votes| %>
            <% tab = (owner && "car#{owner.id}" || "empty-car") %>
            <div class="tab-pane<%= tab_active place, tab %>" id="<%=tab%>">
              <%= car_list owner, votes %>
            </div>
          <% end %>

        <% end %>

      </div>
    </div>

    <ul class="nav nav-tabs">
      <% tab = "info#{place.id}" %>
      <li class="<%= tab_active place, tab %>">
        <a href="#<%=tab%>" data-toggle="tab">
          <i class="icon-info-sign"></i>
        </a>
      </li>
      <% if place.walkable? %>

        <% tab = "people#{place.id}" %>
        <li class="<%= tab_active place, tab %>">
          <a href="#<%=tab%>" data-toggle="tab">
            <span class="label label-inverse"><%= place.votes.count %></span>
            People
          </a>
        </li>

      <% else %>

        <li class="dropdown<%= car_active place %>">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-road"></i>
            Drivers
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <% place.car_owners.each do |owner, votes| %>
              <% tab = (owner && "car#{owner.id}" || "empty-car") %>
              <li class="<%= tab_active place, tab %>">
                <a href="#<%=tab%>" data-toggle="tab">
                  <span class="label label-info"><%= votes.size %></span>
                  <%= owner and owner.name or "Other" %>
                </a>
              </li>
            <% end %>
          </ul>
        </li>

      <% end %>
    </ul>
  </div>
</div>

app/views/places/_place_large.html.erb
<%
icon = mine && 'star' || 'heart'
desc = mine && 'Your Vote' || 'Most Popular Choice'
%>

<% if place %>

<div class="span6">

  <div class="btn-group pull-right">
    <% unless place.people.include? @current_user %>
      <%= link_to '<i class="icon-ok"></i>'.html_safe, votes_path(:place => place), method: :post, remote: true, class: 'btn btn-small' %>
    <% else %>
      <%= link_to '<i class="icon-comment"></i>'.html_safe, edit_vote_path(@current_user.vote), remote: true, class: 'btn btn-small' %>
    <% end %>
    <% if @current_user == place.person %>
      <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_place_path(place), remote: true, class: 'btn btn-small' %>
      <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, place_path(place), method: :delete, confirm: t('places.destroy.confirm'), remote: true, class: 'btn btn-small btn-danger' %>
    <% end %>
  </div>

  <%###### PLACE NAME ######%>
  <h2>
    <i class="icon-<%= icon %>"></i>
    <%= place.name %>
    <small><%= desc %></small>
  </h2>

  <%= place.formatted_notes %>

  <%###### PLACE DETAILS ######%>
  <p>
    <strong>Distance</strong>
    <%= place.walkable? and t('.walking') or t('.driving') %>,
    <strong>Added by</strong>
    <%= place.person.name %><% if place.leaving_at %>,
    <strong>Leaving at</strong>
    <%= place.leaving_at.to_s(:time) %>
    <% end %>
  </p>

  <% if place.walkable? %>

    <%###### WALKING PEOPLE ######%>
    <h4>People</h4>
    <p>
      <% place.people.each do |person| %>
        <% unless person.vote.comment.blank? %>
          <a href="#" rel="tooltip" title="<%= person.vote.comment %>"><i class="icon-comment"></i></a>
        <% else %>
          <i class="icon-user"></i>
        <% end %>
        <%= person.name %>
      <% end %>

      <% if place.people.include? @current_user %>
        <%= link_to t('.unvote_html'), vote_path(@current_user.vote), method: :delete, remote: true, class: 'btn btn-mini btn-danger' %>
      <% else %>
        <%= link_to t(".vote_html"), votes_path(:place => place), method: :post, remote: true, class: 'btn btn-mini btn-primary' %>
      <% end %>
    </p>

  <% else %>

    <%###### DRIVING PEOPLE ######%>
    <div class="well container-fluid">
      <div class="row-fluid">
        <% place.car_owners.each do |owner, votes| %>
        <div class="span3">
          <%= car_list owner, votes %>
          <% if votes.include? @current_user.vote %>
            <%= link_to t('.unvote_html'), vote_path(@current_user.vote), method: :delete, remote: true, class: 'btn btn-mini btn-danger' %>
          <% else %>
            <%= link_to t(".vote_html"), votes_path(:place => place, :car => owner.try(:car)), method: :post, remote: true, class: 'btn btn-mini btn-primary' %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

<% elsif mine %>

<div class="span6 no-vote">
  <p>You haven't chosen a place to eat yet!</p>
  <p class="subtext">
    Try clicking one of the
    <a href="#" class="btn btn-mini">
      <i class="icon-ok"></i>
    </a>
    Join buttons to choose a place to go.
  </p>
</div>

<% end %>

app/views/places/_places.html.erb
<% if @their_place %>

<div class="container-fluid">
  <div class="row-fluid">
    <% if @my_place == @their_place %>
      <div class="span3">&nbsp;</div>
      <%= render partial: 'places/place_large', locals: {place: @their_place, mine: false} %>
    <% else %>
      <%= render partial: 'places/place_large', locals: {place: @my_place, mine: true} %>
      <%= render partial: 'places/place_large', locals: {place: @their_place, mine: false} %>
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <h2>Other Places</h2>

  <% @places.in_groups_of(4, false).each do |group| -%>
  <div class="row-fluid">
    <% group.each do |p| %>
    <%= render partial: 'places/place_cell', locals: {place: p} %>
    <% end %>
  </div>
  <% end %>
</div>

<% else %>

<div class="container-fluid">
  <div class="row-fluid">

    <div class="span3">&nbsp;</div>
    <div class="no-vote span6">
      <p>No one has suggested a place yet!</p>
      <p class="subtext">
        Why don't you
        <a href="#add-place" data-toggle="modal" class="btn btn-mini">
          <i class="icon-plus"></i>
          add a new place
        </a>
        ?
      </p>
    </div>

  </div>
</div>

<% end %>

app/views/places/create.js.erb
<% if @place.valid? %>
updatePlaces();
$('#add-place').modal('hide');
<%= js_notice t('.success', :name => @place.name) %>
<% else %>
<%= js_error @place %>
<% end %>

app/views/places/destroy.js.erb
updatePlaces();
<%= js_notice t('.success', :name => @place.name) %>

app/views/places/edit.js.erb
(function() {
  this.html("<%= escape_javascript render(partial: 'place', locals: {place: @place}) %>");
  this.modal()
}).call($('#edit-place'));

app/views/places/index.html.erb
<div id="add-place" class="modal fade">
  <%= render :partial => 'place', :locals => {:place => @new_place} %>
</div>

<div id="places">
  <%= render :partial => 'places' %>
</div>


<div id="edit-place" class="modal fade"></div>
<div id="comment" class="modal fade"></div>

app/views/places/update.js.erb
<% if @place.valid? %>
updatePlaces();
$('#edit-place').modal('hide');
<%= js_notice t('.success', :name => @place.name) %>
<% else %>
<%= js_error @place %>
<% end %>