config/routes.rb
Lunch::Application.routes.draw do
  resource :car_options
  resources :votes
  resources :people
  resources :places
  match 'periodic' => 'places#periodic'
  
  match 'login' => 'people#login', :as => :login
  match 'logout' => 'people#logout', :as => :logout
  match 'profile' => 'people#edit', :as => :profile

  root :to => "places#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vote for Lunch</title>
  <link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap-responsive.min.css" />
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @current_user and "logged-in" or "logged-out" %>">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to t('.title'), places_path, class: 'brand' %>

        <% if @current_user %>

        <ul class="nav">
          <li>
            <a href="#add-place" data-toggle="modal">
              <i class="icon-plus icon-white"></i>
              Add a New Place
            </a>
          </li>
        </ul>

        <ul class="nav pull-right">
          <li>
            <a data-toggle="modal" href="#options">
              <i class="icon-white icon-cog"></i>
              <%= t '.options.link' %>
            </a>
          </li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-white icon-user"></i> <%= @current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('.profile'), profile_url %></li>
              <li><%= link_to t('.logout'), logout_url %></li>
            </ul>
          </li>
        </ul>

        <% else %>

        <ul class="nav">
          <li><%= link_to t('.login'), login_url %></li>
          <li><%= link_to t('.signup'), new_person_url %></li>
        </ul>

        <% end %>
      </div>
    </div>
  </div>

	<div id="messages">
	  <div class="alert alert-error" style="<%= 'display:none' unless flash.key?(:error) %>">
	    <a class="close" data-dismiss="alert">x</a>
	    <span class="message"><%= flash[:error] %></span>
	  </div>
	  <div class="alert alert-success" style="display:none">
	    <a class="close" data-dismiss="alert">x</a>
	    <span class="message"></span>
	  </div>
	</div>

	<div id="container">
	  <%= yield %>
	</div>

	<% if @current_user %>
	<div id="options" class="modal fade">
	  <%= form_tag car_options_url, method: :put, remote: true, class: 'form-horizontal' do |f| -%>
	  <div class="modal-header">
	    <a class="close" data-dismiss="modal">x</a>
	    <h3><%=t '.options.heading' %></h3>
	  </div>
	  <div class="modal-body">
	    <label class="checkbox">
	      <%= check_box_tag :has_car, '1', @current_user.has_car? %> <%= t '.options.have_car' %>
	    </label>
	    <label class="input-append" id="seat_count">
	      <%= t '.options.seats_html', :field => number_field_tag(:seats, @current_car.seats, size: 5, step: 1, in: 1..10, class: 'input-mini') %>
	    </label>
	  </div>
	  <div class="modal-footer">
      <button class="btn" data-dismiss="modal">Cancel</button>
      <%= submit_tag t('.options.submit'), class: 'btn btn-primary' %>
	  </div>
    <% end %>
	</div>
	<% end %>

  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "application" %>
</body>
</html>